{% set version = "1.7.0" %}

package:
  name: hunspell
  version: {{ version }}

source:
  url: https://github.com/hunspell/hunspell/archive/v{{ version }}.tar.gz
  sha256: bb27b86eb910a8285407cf3ca33b62643a02798cf2eef468c0a74f6c3ee6bc8a

build:
  number: 1002

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - make  # [unix]
    - m2-autoconf  # [win]
    - m2-automake-wrapper  # [win]
    - m2-bash  # [win]
    - m2-grep  # [win]
    - m2-libtool  # [win]
    - m2-m4  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
  host:
    - gettext  # [unix]
    - readline  # [unix]
    - m2-ncurses  # [win]
    - m2-libreadline  # [win]
    - libiconv  # [win]
  run:
    - gettext  # [unix]
    - readline  # [unix]
    - m2-ncurses  # [win]
    - m2-libreadline  # [win]
    - libiconv  # [win]

test:
  commands:
    - hunspell --help

about:
  home: https://hunspell.github.io
  license: MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: The most popular spellchecking library.
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  doc_url: https://hunspell.github.io
  dev_url: https://github.com/hunspell/hunspell

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - bollwyvl
