{% set version = "1.7.2" %}

package:
  name: hunspell
  version: {{ version }}

source:
  url: https://github.com/hunspell/hunspell/archive/v{{ version }}.tar.gz
  sha256: 69fa312d3586c988789266eaf7ffc9861d9f6396c31fc930a014d551b59bbd6e

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - gettext
    - readline
  run:
    - gettext
    - readline

test:
  commands:
    - hunspell --help
    - hunspell -D

about:
  home: http://hunspell.github.io
  license: MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
    - COPYING.MPL
  summary: The most popular spellchecking library.
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  doc_url: http://hunspell.github.io
  dev_url: https://github.com/hunspell/hunspell

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
