# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.7.3"
  build_number: 0
  dict_path: share/hunspell
  legacy_path: share/hunspell_dictionaries

package:
  name: hunspell
  version: ${{ version }}

source:
  url: https://github.com/hunspell/hunspell/archive/v${{ version }}.tar.gz
  sha256: 933be3dac6fd55f6e752331a170efb7e33800e40fae1156d8434cc8c85379a1b

build:
  number: ${{ build_number }}
  skip: win
  script:
    - autoreconf -vfi
    - ./configure "--prefix=${PREFIX}" --with-readline --with-ui
    - make "-j${CPU_COUNT}"
    - if: host_platform == target_platform
      then:
        - make check "-j${CPU_COUNT}"
    - make install
    - mkdir -p "${PREFIX}/${{ dict_path }}"
    # rattler-build doesn't ship empty directories: https://github.com/prefix-dev/rattler-build/issues/371
    - echo "" >> "${PREFIX}/${{ dict_path }}/.empty"
    # legacy path symlink
    - ln -s "${PREFIX}/${{ dict_path }}" "${PREFIX}/${{ legacy_path }}"

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - gettext
    - libiconv
    - ncurses
    - readline

tests:
  - package_contents:
      bin:
        - affixcompress
        - analyze
        - chmorph
        - hunspell
        - hunzip
        - hzip
        - ispellaff2myspell
        - makealias
        - munch
        - unmunch
        - wordforms
        - wordlist2hunspell
  - script:
      env:
        # conda-forge CI seems to use en_US, set something `hunspell -D`
        LANG: en_GB
      content:
        # build a fake dictionary
        - cd "${CONDA_PREFIX}/${{ dict_path }}"
        - echo "ok" > test.words
        - wordlist2hunspell test.words "${LANG}"
        - rm test.words
        - cd "${SRC_DIR}"
        # check basic commands
        - hunspell --help
        - hunspell --version
        - hunspell -D
        - hunspell --version | grep -iE "\(but really Hunspell ${{ version | replace(".", "\\.") }}\)"
        - hunspell -D 2>&1 | grep -iE "^\.::${CONDA_PREFIX}/${{ dict_path }}:"
        - hunspell -D 2>&1 | grep -iE "${CONDA_PREFIX}/${{ dict_path }}/${LANG}.dic"
        - hunspell -D 2>&1 | grep -iE "${CONDA_PREFIX}/${{ dict_path }}/${LANG}.aff"
        # check symlink
        - ls "${CONDA_PREFIX}/${{ legacy_path }}/en_US.dic"

about:
  license: MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
    - COPYING.MPL
  summary: The most popular spellchecking library.
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  homepage: http://hunspell.github.io
  repository: https://github.com/hunspell/hunspell

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - bollwyvl
