# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.7.3"
  build_number: 0
  dict_path: share/hunspell
  legacy_path: share/hunspell_dictionaries

recipe:
  name: hunspell
  version: ${{ version }}

source:
  url: https://github.com/hunspell/hunspell/archive/v${{ version }}.tar.gz
  sha256: 933be3dac6fd55f6e752331a170efb7e33800e40fae1156d8434cc8c85379a1b

build:
  number: ${{ build_number }}
  skip: win

outputs:
  - package:
      name: hunspell
    build:
      script:
        - autoreconf -vfi
        - ./configure "--prefix=${PREFIX}" --with-readline --with-ui
        - make "-j${CPU_COUNT}"
        - if: host_platform == target_platform
          then:
            - make check "-j${CPU_COUNT}"
        - make install
        - mkdir -p "${PREFIX}/${{ dict_path }}"
        # rattler-build doesn't ship empty directories: https://github.com/prefix-dev/rattler-build/issues/371
        - echo "" >> "${PREFIX}/share/${{ dict_path }}/.empty"
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - autoconf
        - automake
        - libtool
        - make
        - pkg-config
      host:
        - gettext
        - libiconv
        - readline
    tests:
      - package_contents:
          bin:
            - affixcompress
            - analyze
            - chmorph
            - hunspell
            - hunzip
            - hzip
            - ispellaff2myspell
            - makealias
            - munch
            - unmunch
            - wordforms
            - wordlist2hunspell
      - script:
          content:
            - hunspell --help
            - hunspell --version
            - echo "... checking reported version is ${{ version }}"
            - hunspell --version | grep -iE "\(but really Hunspell ${{ version | replace(".", "\\.") }}\)"
            # build a fake dictionary
            - cd "${CONDA_PREFIX}/${{ dict_path }}"
            - echo "ok" > test.words
            # TODO: verify conda-forge CI always uses en_US?
            - wordlist2hunspell test.words en_US
            - rm test.words
            - cd "${SRC_DIR}"
            # check paths
            - hunspell -D
            - echo "... checking for dictionary path in ${CONDA_PREFIX}"
            - hunspell -D 2>&1 | grep -iE "^\.::${CONDA_PREFIX}/${{ dict_path }}:"
            - echo "... checking for dictionaries"
            - hunspell -D 2>&1 | grep -iE "${CONDA_PREFIX}/${{ dict_path }}/en_US.dic"
            - hunspell -D 2>&1 | grep -iE "${CONDA_PREFIX}/${{ dict_path }}/en_US.aff"

  - package:
      name: hunspell-dictionaries-legacy-path
    build:
      noarch: generic
      # overload build string to upload exactly once
      string: noarch_${{ build_number }}
      script:
        - ln -s "${PREFIX}/${{ legacy_path }}/" "${PREFIX}/${{ dict_path }}/"
    requirements:
      host:
        - ${{ pin_subpackage("hunspell", upper_bound="x.x.x") }}
      run:
        - ${{ pin_subpackage("hunspell", upper_bound="x.x.x") }}
        # avoid windows symlink check: https://github.com/prefix-dev/rattler-build/pull/2167
        - __unix
    tests:
      - script:
          - ls "${PREFIX}/${{ legacy_path }}/.empty"
    about:
      summary: Legacy symlink for PREFIX/${{ legacy_path }} to PREFIX/${{ dict_path }}
      description: |
        Please avoid using this package and update to hunspell 1.7.3 and PREFIX/${{ dict_path }}

about:
  license: MPL-1.1 AND GPL-2.0-or-later AND LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
    - COPYING.MPL
  summary: The most popular spellchecking library.
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  homepage: http://hunspell.github.io
  repository: https://github.com/hunspell/hunspell

extra:
  feedstock-name: hunspell
  recipe-maintainers:
    - scopatz
    - asmeurer
    - bollwyvl
